name: Linter

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2020.04.05'

      - uses: actions/checkout@v2

      - name: Run clj-kondo
        run: clj-kondo --lint src

